//! Generates CLI and preset reference pages for the AgX documentation site.
//!
//! Output is written to `docs/book/src/reference/` and consumed by mdbook.

use std::{fs, io, path::PathBuf};

use clap_markdown::MarkdownOptions;

const OUTPUT_DIR: &str = "docs/book/src/reference";
const OUTPUT_FILE: &str = "cli.md";
const GENERATED_HEADER: &str = "<!-- Generated by agx-docgen. Do not edit manually. -->";
const PAGE_TITLE: &str = "# CLI Reference";
const CLAP_MARKDOWN_TITLE: &str = "# Command-Line Help for `agx`";

fn main() {
    if let Err(error) = generate_cli_reference() {
        eprintln!("agx-docgen: {error}");
        std::process::exit(1);
    }
}

fn generate_cli_reference() -> io::Result<PathBuf> {
    let output_dir = repo_root().join(OUTPUT_DIR);
    fs::create_dir_all(&output_dir)?;

    let command = agx_cli::build_cli();
    let markdown = clap_markdown::help_markdown_command_custom(
        &command,
        &MarkdownOptions::new().show_footer(false),
    );
    let markdown = sanitize_markdown(&markdown);

    let output_path = output_dir.join(OUTPUT_FILE);
    let contents = format!("{GENERATED_HEADER}\n{PAGE_TITLE}\n\n{markdown}");
    fs::write(&output_path, contents)?;

    println!("generated {}", output_path.display());

    Ok(output_path)
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("agx-docgen must live under crates/")
        .to_path_buf()
}

fn sanitize_markdown(markdown: &str) -> String {
    let markdown = strip_clap_markdown_title(markdown);
    strip_alias_annotations(&markdown)
}

fn strip_clap_markdown_title(markdown: &str) -> String {
    let Some(first_line_end) = markdown.find('\n') else {
        return markdown.to_owned();
    };

    let first_line = &markdown[..first_line_end];
    if first_line != CLAP_MARKDOWN_TITLE {
        return markdown.to_owned();
    }

    let mut remainder = &markdown[first_line_end + 1..];
    if remainder.starts_with('\n') {
        remainder = &remainder[1..];
    }

    remainder.to_owned()
}

fn strip_alias_annotations(markdown: &str) -> String {
    markdown
        .replace(" [alias: ", " (alias: ")
        .replace(" [aliases: ", " (aliases: ")
        .replace("`] —", "`) —")
        .replace("`] \n", "`) \n")
        .replace("`]\n", "`)\n")
}

#[cfg(test)]
mod tests {
    use super::{
        repo_root, sanitize_markdown, strip_alias_annotations, strip_clap_markdown_title,
    };

    #[test]
    fn repo_root_points_at_workspace_root() {
        let root = repo_root();

        assert!(root.ends_with("AgX"));
        assert!(root.join("docs/book/src/reference/cli.md").is_absolute());
    }

    #[test]
    fn strip_clap_markdown_title_removes_only_the_known_title() {
        let markdown = "# Command-Line Help for `agx`\n\n## `agx`\n\n###### **Subcommands:**\n";

        let stripped = strip_clap_markdown_title(markdown);

        assert_eq!(stripped, "## `agx`\n\n###### **Subcommands:**\n");
    }

    #[test]
    fn strip_clap_markdown_title_leaves_other_headings_alone() {
        let markdown = "# Something Else\n\n## `agx`\n";

        let stripped = strip_clap_markdown_title(markdown);

        assert_eq!(stripped, markdown);
    }

    #[test]
    fn strip_alias_annotations_rewrites_alias_markers_for_mdbook() {
        let markdown = "* `--hsl-red-hue <HSL_RED_HUE>` [alias: `hsl-red-h`] — Red hue shift\n";

        let sanitized = strip_alias_annotations(markdown);

        assert_eq!(
            sanitized,
            "* `--hsl-red-hue <HSL_RED_HUE>` (alias: `hsl-red-h`) — Red hue shift\n"
        );
    }

    #[test]
    fn sanitize_markdown_applies_title_and_alias_rewrites() {
        let markdown = "# Command-Line Help for `agx`\n\n* `--x` [alias: `y`] — Help\n";

        let sanitized = sanitize_markdown(markdown);

        assert_eq!(sanitized, "* `--x` (alias: `y`) — Help\n");
    }
}
