//! Generates CLI and preset reference pages for the AgX documentation site.
//!
//! Output is written to `docs/book/src/reference/` and consumed by mdbook.

use std::{
    fs, io,
    path::{Path, PathBuf},
};

use clap_markdown::MarkdownOptions;
use schemars::schema::{InstanceType, RootSchema, Schema, SchemaObject, SingleOrVec};

const OUTPUT_DIR: &str = "docs/book/src/reference";
const CLI_OUTPUT_FILE: &str = "cli.md";
const PRESET_OUTPUT_FILE: &str = "preset.md";
const GENERATED_HEADER: &str = "<!-- Generated by agx-docgen. Do not edit manually. -->";
const CLI_PAGE_TITLE: &str = "# CLI Reference";
const PRESET_PAGE_TITLE: &str = "# Preset Format Reference";
const CLAP_MARKDOWN_TITLE: &str = "# Command-Line Help for `agx`";
const TONE_FIELDS: &[&str] = &[
    "exposure",
    "contrast",
    "highlights",
    "shadows",
    "whites",
    "blacks",
];
const WHITE_BALANCE_FIELDS: &[&str] = &["temperature", "tint"];
const MANUAL_METADATA_FIELDS: &[(&str, &str, &str, &str)] = &[
    (
        "metadata.name",
        "string",
        "\"\"",
        "Human-readable preset name.",
    ),
    (
        "metadata.version",
        "string",
        "\"\"",
        "Semantic version string for the preset.",
    ),
    ("metadata.author", "string", "\"\"", "Preset author name."),
    (
        "metadata.extends",
        "string or null",
        "null",
        "Optional relative path to a base preset TOML file to merge before this preset.",
    ),
];
const MANUAL_LUT_FIELDS: &[(&str, &str, &str, &str)] = &[
    (
        "lut.path",
        "string or null",
        "null",
        "Optional relative path to a `.cube` LUT file, resolved from the preset TOML file.",
    ),
    (
        "lut.encoding",
        "`srgb`, `linear`",
        "`srgb`",
        "Color space the LUT was authored in. `srgb` = sRGB transfer curve (standard for creative LUTs). `linear` = linear light, sRGB primaries. Both variants assume sRGB primaries. Applies to the LUT loaded via this preset's `path`; inheriting a base preset's LUT without also specifying `path` leaves the encoding unchanged.",
    ),
];
const HSL_CHANNELS: &[&str] = &[
    "red", "orange", "yellow", "green", "aqua", "blue", "purple", "magenta",
];
const HSL_COMPONENTS: &[&str] = &["hue", "saturation", "luminance"];

fn main() {
    if let Err(error) = generate_cli_reference().and_then(|_| generate_preset_reference()) {
        eprintln!("agx-docgen: {error}");
        std::process::exit(1);
    }
}

fn generate_cli_reference() -> io::Result<PathBuf> {
    let output_dir = repo_root().join(OUTPUT_DIR);
    fs::create_dir_all(&output_dir)?;

    let command = agx_cli::build_cli();
    let markdown = clap_markdown::help_markdown_command_custom(
        &command,
        &MarkdownOptions::new().show_footer(false),
    );
    let markdown = sanitize_markdown(&markdown);

    let output_path = output_dir.join(CLI_OUTPUT_FILE);
    let contents = format!("{GENERATED_HEADER}\n{CLI_PAGE_TITLE}\n\n{markdown}");
    fs::write(&output_path, contents)?;

    println!("generated {}", output_path.display());

    Ok(output_path)
}

fn generate_preset_reference() -> io::Result<PathBuf> {
    let output_dir = repo_root().join(OUTPUT_DIR);
    let output_path = output_dir.join(PRESET_OUTPUT_FILE);
    generate_preset_reference_to(&output_path)
}

fn generate_preset_reference_to(output_path: &Path) -> io::Result<PathBuf> {
    let output_dir = output_path
        .parent()
        .expect("preset output path should have a parent directory");
    fs::create_dir_all(output_dir)?;

    let schema = schemars::schema_for!(agx::Parameters);
    let contents = render_preset_reference(&schema);
    fs::write(output_path, contents)?;

    println!("generated {}", output_path.display());

    Ok(output_path.to_path_buf())
}

fn render_preset_reference(schema: &RootSchema) -> String {
    let mut sections = Vec::new();
    sections.push(render_manual_section(
        "metadata",
        "Preset metadata, including name, version, author, and optional inheritance.",
        MANUAL_METADATA_FIELDS,
    ));
    sections.push(render_prefixed_flat_section(
        schema,
        "tone",
        "Controls exposure, contrast, highlights, shadows, whites, and blacks.",
        TONE_FIELDS,
    ));
    sections.push(render_prefixed_flat_section(
        schema,
        "white_balance",
        "Controls temperature and tint shifts applied before tonal adjustments.",
        WHITE_BALANCE_FIELDS,
    ));
    sections.push(render_manual_section(
        "lut",
        "Optional 3D LUT reference loaded from a `.cube` file.",
        MANUAL_LUT_FIELDS,
    ));
    sections.push(render_hsl_section(schema));
    sections.push(render_nested_section(
        schema,
        "vignette",
        "Controls creative edge darkening or brightening.",
        "vignette",
    ));
    sections.push(render_nested_section(
        schema,
        "color_grading",
        "Controls shadows, midtones, highlights, and global color wheels.",
        "color_grading",
    ));
    sections.push(render_nested_section(
        schema,
        "tone_curve",
        "Controls five independent tone curves for RGB, luma, and per-channel adjustments.",
        "tone_curve",
    ));
    sections.push(render_nested_section(
        schema,
        "detail",
        "Controls sharpening, clarity, and texture adjustments.",
        "detail",
    ));
    sections.push(render_nested_section(
        schema,
        "dehaze",
        "Controls atmospheric haze removal or addition.",
        "dehaze",
    ));
    sections.push(render_nested_section(
        schema,
        "noise_reduction",
        "Controls luminance and chroma noise reduction.",
        "noise_reduction",
    ));
    sections.push(render_nested_section(
        schema,
        "grain",
        "Controls film grain simulation.",
        "grain",
    ));

    format!(
        "{GENERATED_HEADER}\n{PRESET_PAGE_TITLE}\n\n\
         This page documents every field available in an AgX preset TOML file, organized by on-disk table.\n\n\
         {}\n",
        sections.join("\n")
    )
}

fn render_manual_section(
    title: &str,
    description: &str,
    rows: &[(&str, &str, &str, &str)],
) -> String {
    let mut section = format!("## {title}\n\n{description}\n\n{}", markdown_table_header());
    for &(field, range, default, note) in rows {
        section.push_str(&format_manual_row(field, range, default, note));
    }
    section.push('\n');
    section
}

fn render_prefixed_flat_section(
    schema: &RootSchema,
    section_name: &str,
    description: &str,
    fields: &[&str],
) -> String {
    let mut section = format!(
        "## {section_name}\n\n{description}\n\n{}",
        markdown_table_header()
    );
    for &field in fields {
        let display_name = format!("{section_name}.{field}");
        let schema_path = vec![field];
        section.push_str(&format_field_row(schema, &schema_path, &display_name));
    }
    section.push('\n');
    section
}

fn format_field_row(schema: &RootSchema, field_path: &[&str], field_name: &str) -> String {
    let field_schema = schema_at_path(schema, field_path);
    format!(
        "| `{}` | {} | {} | {} |\n",
        field_name,
        escape_table_cell(&get_range_string(schema, field_path, field_schema)),
        escape_table_cell(&get_default_string(field_path, field_schema)),
        escape_table_cell(&get_description(field_schema))
    )
}

fn format_manual_row(field_name: &str, range: &str, default: &str, note: &str) -> String {
    format!(
        "| `{}` | {} | {} | {} |\n",
        field_name,
        escape_table_cell(range),
        escape_table_cell(default),
        escape_table_cell(note)
    )
}

fn resolve_ref<'a>(root: &'a RootSchema, schema: &'a SchemaObject) -> &'a SchemaObject {
    let mut current = schema;
    'resolve: loop {
        if let Some(reference) = current.reference.as_deref() {
            current = definition_schema(root, reference);
            continue;
        }

        if let Some(subschemas) = current.subschemas.as_ref() {
            for variants in [&subschemas.all_of, &subschemas.any_of, &subschemas.one_of] {
                if let Some(items) = variants.as_deref() {
                    if items.len() == 1 {
                        current = schema_object(&items[0]);
                        continue 'resolve;
                    }
                }
            }
        }

        return current;
    }
}

fn get_range_string(
    schema: &RootSchema,
    field_path: &[&str],
    field_schema: &SchemaObject,
) -> String {
    let field_schema = resolve_ref(schema, field_schema);

    if let Some(range) = range_override(field_path) {
        return range.to_owned();
    }

    if let Some(enum_values) = field_schema.enum_values.as_ref() {
        if !enum_values.is_empty() {
            return enum_values
                .iter()
                .map(format_json_value)
                .collect::<Vec<_>>()
                .join(", ");
        }
    }

    if let Some(number) = field_schema.number.as_ref() {
        if let (Some(min), Some(max)) = (number.minimum, number.maximum) {
            return format!("{} to {}", format_number(min), format_number(max));
        }
    }

    if let Some(subschemas) = field_schema.subschemas.as_ref() {
        for variants in [&subschemas.any_of, &subschemas.one_of] {
            if let Some(items) = variants.as_deref() {
                let mut enum_values = Vec::new();
                let mut type_values = Vec::new();
                for item in items {
                    let object = resolve_ref(schema, schema_object(item));
                    if let Some(const_value) = object.const_value.as_ref() {
                        enum_values.push(format_json_value(const_value));
                        continue;
                    }
                    if let Some(values) = object.enum_values.as_ref() {
                        enum_values.extend(values.iter().map(format_json_value));
                        continue;
                    }
                    if let Some(type_name) = primitive_type_name(object) {
                        type_values.push(type_name);
                    }
                }
                if !enum_values.is_empty() {
                    enum_values.dedup();
                    return enum_values.join(", ");
                }
                if !type_values.is_empty() {
                    type_values.dedup();
                    return type_values.join(" or ");
                }
            }
        }
    }

    primitive_type_name(field_schema).unwrap_or_else(|| "—".to_owned())
}

fn get_default_string(field_path: &[&str], field_schema: &SchemaObject) -> String {
    if let Some(default) = field_schema
        .metadata
        .as_ref()
        .and_then(|metadata| metadata.default.as_ref())
    {
        return format_json_value(default);
    }

    canonical_default_string(field_path).unwrap_or_else(|| "—".to_owned())
}

fn get_description(field_schema: &SchemaObject) -> String {
    let Some(description) = field_schema
        .metadata
        .as_ref()
        .and_then(|metadata| metadata.description.as_deref())
    else {
        return "—".to_owned();
    };

    let description = description.trim().replace('\n', " ");
    let first_line = description.lines().next().unwrap_or(&description).trim();
    let first_sentence = first_line
        .split_terminator(". ")
        .next()
        .unwrap_or(first_line)
        .trim();

    if first_sentence.ends_with('.') {
        first_sentence.to_owned()
    } else {
        format!("{first_sentence}.")
    }
}

fn render_nested_section(
    schema: &RootSchema,
    title: &str,
    description: &str,
    field_name: &str,
) -> String {
    let mut section = format!("## {title}\n\n{description}\n\n{}", markdown_table_header());

    if let Some(paths) = preferred_nested_field_paths(field_name) {
        for &display_path in paths {
            let (schema_path, display_name) = if field_name == "grain" && display_path == "type" {
                (
                    split_field_path(field_name, "grain_type"),
                    format!("grain.{display_path}"),
                )
            } else {
                (
                    split_field_path(field_name, display_path),
                    format!("{field_name}.{display_path}"),
                )
            };
            section.push_str(&format_field_row(schema, &schema_path, &display_name));
        }
    } else {
        let mut rows = Vec::new();
        collect_leaf_paths(schema, &[field_name], field_name, &mut rows);
        for (path, display_name) in rows {
            let path_refs = path.iter().map(String::as_str).collect::<Vec<_>>();
            let display_name = format!("{field_name}.{display_name}");
            section.push_str(&format_field_row(schema, &path_refs, &display_name));
        }
    }

    section.push('\n');
    if let Some((slug, label)) = explanation_link_for_section(field_name) {
        add_explanation_links(&mut section, slug, label);
    }
    section
}

fn render_hsl_section(schema: &RootSchema) -> String {
    let mut section = format!(
        "## hsl\n\nAdjusts hue, saturation, and luminance for each HSL color channel.\n\n{}",
        markdown_table_header()
    );
    for &channel in HSL_CHANNELS {
        for &component in HSL_COMPONENTS {
            let display = format!("hsl.{channel}.{component}");
            section.push_str(&format_field_row(
                schema,
                &["hsl", channel, component],
                &display,
            ));
        }
    }
    section.push('\n');
    section
}

fn add_explanation_links(section: &mut String, explanation_slug: &str, label: &str) {
    let path = repo_root()
        .join("docs/book/src/explanation/algorithms")
        .join(format!("{explanation_slug}.md"));
    if path.exists() {
        section.push_str(&format!(
            "\nSee [{label}](../explanation/algorithms/{explanation_slug}.md) for details.\n"
        ));
    }
}

fn schema_at_path<'a>(root: &'a RootSchema, path: &[&str]) -> &'a SchemaObject {
    let mut current = &root.schema;
    for segment in path {
        current = property_schema(root, current, segment);
    }
    current
}

fn property_schema<'a>(
    root: &'a RootSchema,
    schema: &'a SchemaObject,
    property: &str,
) -> &'a SchemaObject {
    let resolved = resolve_ref(root, schema);
    let object = resolved
        .object
        .as_ref()
        .unwrap_or_else(|| panic!("schema at '{}' is not an object", property));
    let property_schema = object
        .properties
        .get(property)
        .unwrap_or_else(|| panic!("missing property '{property}'"));
    resolve_ref(root, schema_object(property_schema))
}

fn definition_schema<'a>(root: &'a RootSchema, reference: &str) -> &'a SchemaObject {
    let name = reference
        .strip_prefix("#/definitions/")
        .unwrap_or_else(|| panic!("unsupported schema reference: {reference}"));
    let schema = root
        .definitions
        .get(name)
        .unwrap_or_else(|| panic!("missing schema definition '{name}'"));
    resolve_ref(root, schema_object(schema))
}

fn schema_object(schema: &Schema) -> &SchemaObject {
    match schema {
        Schema::Bool(value) => panic!("unexpected bool schema: {value}"),
        Schema::Object(object) => object,
    }
}

fn collect_leaf_paths(
    root: &RootSchema,
    path: &[&str],
    display_name: &str,
    rows: &mut Vec<(Vec<String>, String)>,
) {
    let schema = schema_at_path(root, path);
    let schema = resolve_ref(root, schema);
    if let Some(object) = schema.object.as_ref() {
        if !object.properties.is_empty() {
            let property_names = object
                .properties
                .keys()
                .map(String::as_str)
                .collect::<Vec<_>>();
            for property in property_names {
                let mut next_path = path.to_vec();
                next_path.push(property);
                let next_display = if display_name.is_empty() {
                    property.to_owned()
                } else {
                    format!("{display_name}.{property}")
                };
                collect_leaf_paths(root, &next_path, &next_display, rows);
            }
            return;
        }
    }

    rows.push((
        path.iter().map(|segment| (*segment).to_owned()).collect(),
        display_name.to_owned(),
    ));
}

fn markdown_table_header() -> &'static str {
    "| Field | Range / Values | Default | Note |\n| --- | --- | --- | --- |\n"
}

fn escape_table_cell(value: &str) -> String {
    value
        .replace('|', "\\|")
        .replace('[', "&#91;")
        .replace(']', "&#93;")
        .replace('\n', " ")
}

fn format_json_value(value: &impl std::fmt::Display) -> String {
    let rendered = value.to_string();
    if rendered.starts_with('"') && rendered.ends_with('"') && rendered.len() >= 2 {
        return format!("`{}`", &rendered[1..rendered.len() - 1]);
    }
    if let Ok(number) = rendered.parse::<f64>() {
        return format_number(number);
    }
    rendered
}

fn format_number(value: f64) -> String {
    let mut formatted = value.to_string();
    if let Some(stripped) = formatted.strip_suffix(".0") {
        formatted = stripped.to_owned();
    }
    formatted
}

fn primitive_type_name(schema: &SchemaObject) -> Option<String> {
    match schema.instance_type.as_ref()? {
        SingleOrVec::Single(instance) => Some(instance_type_name(instance).to_owned()),
        SingleOrVec::Vec(instances) => {
            let names = instances.iter().map(instance_type_name).collect::<Vec<_>>();
            if names.is_empty() {
                None
            } else {
                Some(names.join(" or "))
            }
        }
    }
}

fn instance_type_name(instance: &InstanceType) -> &'static str {
    match instance {
        InstanceType::Null => "null",
        InstanceType::Boolean => "boolean",
        InstanceType::Object => "object",
        InstanceType::Array => "array",
        InstanceType::Number => "number",
        InstanceType::String => "string",
        InstanceType::Integer => "integer",
    }
}

fn canonical_default_string(field_path: &[&str]) -> Option<String> {
    let defaults = agx::Parameters::default();

    match field_path {
        ["exposure"] | ["tone", "exposure"] => Some(format_f32_default(defaults.exposure)),
        ["contrast"] | ["tone", "contrast"] => Some(format_f32_default(defaults.contrast)),
        ["highlights"] | ["tone", "highlights"] => Some(format_f32_default(defaults.highlights)),
        ["shadows"] | ["tone", "shadows"] => Some(format_f32_default(defaults.shadows)),
        ["whites"] | ["tone", "whites"] => Some(format_f32_default(defaults.whites)),
        ["blacks"] | ["tone", "blacks"] => Some(format_f32_default(defaults.blacks)),
        ["temperature"] | ["white_balance", "temperature"] => {
            Some(format_f32_default(defaults.temperature))
        }
        ["tint"] | ["white_balance", "tint"] => Some(format_f32_default(defaults.tint)),
        ["hsl", "red", "hue"] => Some(format_f32_default(defaults.hsl.red.hue)),
        ["hsl", "red", "saturation"] => Some(format_f32_default(defaults.hsl.red.saturation)),
        ["hsl", "red", "luminance"] => Some(format_f32_default(defaults.hsl.red.luminance)),
        ["hsl", "orange", "hue"] => Some(format_f32_default(defaults.hsl.orange.hue)),
        ["hsl", "orange", "saturation"] => Some(format_f32_default(defaults.hsl.orange.saturation)),
        ["hsl", "orange", "luminance"] => Some(format_f32_default(defaults.hsl.orange.luminance)),
        ["hsl", "yellow", "hue"] => Some(format_f32_default(defaults.hsl.yellow.hue)),
        ["hsl", "yellow", "saturation"] => Some(format_f32_default(defaults.hsl.yellow.saturation)),
        ["hsl", "yellow", "luminance"] => Some(format_f32_default(defaults.hsl.yellow.luminance)),
        ["hsl", "green", "hue"] => Some(format_f32_default(defaults.hsl.green.hue)),
        ["hsl", "green", "saturation"] => Some(format_f32_default(defaults.hsl.green.saturation)),
        ["hsl", "green", "luminance"] => Some(format_f32_default(defaults.hsl.green.luminance)),
        ["hsl", "aqua", "hue"] => Some(format_f32_default(defaults.hsl.aqua.hue)),
        ["hsl", "aqua", "saturation"] => Some(format_f32_default(defaults.hsl.aqua.saturation)),
        ["hsl", "aqua", "luminance"] => Some(format_f32_default(defaults.hsl.aqua.luminance)),
        ["hsl", "blue", "hue"] => Some(format_f32_default(defaults.hsl.blue.hue)),
        ["hsl", "blue", "saturation"] => Some(format_f32_default(defaults.hsl.blue.saturation)),
        ["hsl", "blue", "luminance"] => Some(format_f32_default(defaults.hsl.blue.luminance)),
        ["hsl", "purple", "hue"] => Some(format_f32_default(defaults.hsl.purple.hue)),
        ["hsl", "purple", "saturation"] => Some(format_f32_default(defaults.hsl.purple.saturation)),
        ["hsl", "purple", "luminance"] => Some(format_f32_default(defaults.hsl.purple.luminance)),
        ["hsl", "magenta", "hue"] => Some(format_f32_default(defaults.hsl.magenta.hue)),
        ["hsl", "magenta", "saturation"] => {
            Some(format_f32_default(defaults.hsl.magenta.saturation))
        }
        ["hsl", "magenta", "luminance"] => Some(format_f32_default(defaults.hsl.magenta.luminance)),
        ["vignette", "amount"] => Some(format_f32_default(defaults.vignette.amount)),
        ["vignette", "shape"] => Some(format_display_default(defaults.vignette.shape)),
        ["color_grading", "shadows", "hue"] => {
            Some(format_f32_default(defaults.color_grading.shadows.hue))
        }
        ["color_grading", "shadows", "saturation"] => Some(format_f32_default(
            defaults.color_grading.shadows.saturation,
        )),
        ["color_grading", "shadows", "luminance"] => {
            Some(format_f32_default(defaults.color_grading.shadows.luminance))
        }
        ["color_grading", "midtones", "hue"] => {
            Some(format_f32_default(defaults.color_grading.midtones.hue))
        }
        ["color_grading", "midtones", "saturation"] => Some(format_f32_default(
            defaults.color_grading.midtones.saturation,
        )),
        ["color_grading", "midtones", "luminance"] => Some(format_f32_default(
            defaults.color_grading.midtones.luminance,
        )),
        ["color_grading", "highlights", "hue"] => {
            Some(format_f32_default(defaults.color_grading.highlights.hue))
        }
        ["color_grading", "highlights", "saturation"] => Some(format_f32_default(
            defaults.color_grading.highlights.saturation,
        )),
        ["color_grading", "highlights", "luminance"] => Some(format_f32_default(
            defaults.color_grading.highlights.luminance,
        )),
        ["color_grading", "global", "hue"] => {
            Some(format_f32_default(defaults.color_grading.global.hue))
        }
        ["color_grading", "global", "saturation"] => {
            Some(format_f32_default(defaults.color_grading.global.saturation))
        }
        ["color_grading", "global", "luminance"] => {
            Some(format_f32_default(defaults.color_grading.global.luminance))
        }
        ["color_grading", "balance"] => Some(format_f32_default(defaults.color_grading.balance)),
        ["tone_curve", "rgb", "points"] => {
            Some(format_points_default(&defaults.tone_curve.rgb.points))
        }
        ["tone_curve", "luma", "points"] => {
            Some(format_points_default(&defaults.tone_curve.luma.points))
        }
        ["tone_curve", "red", "points"] => {
            Some(format_points_default(&defaults.tone_curve.red.points))
        }
        ["tone_curve", "green", "points"] => {
            Some(format_points_default(&defaults.tone_curve.green.points))
        }
        ["tone_curve", "blue", "points"] => {
            Some(format_points_default(&defaults.tone_curve.blue.points))
        }
        ["detail", "sharpening", "amount"] => {
            Some(format_f32_default(defaults.detail.sharpening.amount))
        }
        ["detail", "sharpening", "radius"] => {
            Some(format_f32_default(defaults.detail.sharpening.radius))
        }
        ["detail", "sharpening", "threshold"] => {
            Some(format_f32_default(defaults.detail.sharpening.threshold))
        }
        ["detail", "sharpening", "masking"] => {
            Some(format_f32_default(defaults.detail.sharpening.masking))
        }
        ["detail", "clarity"] => Some(format_f32_default(defaults.detail.clarity)),
        ["detail", "texture"] => Some(format_f32_default(defaults.detail.texture)),
        ["dehaze", "amount"] => Some(format_f32_default(defaults.dehaze.amount)),
        ["noise_reduction", "luminance"] => {
            Some(format_f32_default(defaults.noise_reduction.luminance))
        }
        ["noise_reduction", "color"] => Some(format_f32_default(defaults.noise_reduction.color)),
        ["noise_reduction", "detail"] => Some(format_f32_default(defaults.noise_reduction.detail)),
        ["grain", "grain_type"] => Some(format_display_default(defaults.grain.grain_type)),
        ["grain", "amount"] => Some(format_f32_default(defaults.grain.amount)),
        ["grain", "size"] => Some(format_f32_default(defaults.grain.size)),
        ["grain", "seed"] => Some(format_option_u64_default(defaults.grain.seed)),
        _ => None,
    }
}

fn range_override(field_path: &[&str]) -> Option<&'static str> {
    match field_path {
        ["temperature"] | ["white_balance", "temperature"] => Some("number (no validated range)"),
        ["tint"] | ["white_balance", "tint"] => Some("number (no validated range)"),
        ["tone_curve", _, "points"] => Some("array of &#91;x, y&#93; points, each 0 to 1"),
        _ => None,
    }
}

fn preferred_nested_field_paths(field_name: &str) -> Option<&'static [&'static str]> {
    match field_name {
        "vignette" => Some(&["amount", "shape"]),
        "color_grading" => Some(&[
            "shadows.hue",
            "shadows.saturation",
            "shadows.luminance",
            "midtones.hue",
            "midtones.saturation",
            "midtones.luminance",
            "highlights.hue",
            "highlights.saturation",
            "highlights.luminance",
            "global.hue",
            "global.saturation",
            "global.luminance",
            "balance",
        ]),
        "tone_curve" => Some(&[
            "rgb.points",
            "luma.points",
            "red.points",
            "green.points",
            "blue.points",
        ]),
        "detail" => Some(&[
            "sharpening.amount",
            "sharpening.radius",
            "sharpening.threshold",
            "sharpening.masking",
            "clarity",
            "texture",
        ]),
        "dehaze" => Some(&["amount"]),
        "noise_reduction" => Some(&["luminance", "color", "detail"]),
        "grain" => Some(&["type", "amount", "size", "seed"]),
        _ => None,
    }
}

fn split_field_path<'a>(base: &'a str, display_path: &'a str) -> Vec<&'a str> {
    let mut parts = vec![base];
    parts.extend(display_path.split('.'));
    parts
}

fn explanation_link_for_section(field_name: &str) -> Option<(&'static str, &'static str)> {
    match field_name {
        "grain" => Some(("grain", "Grain")),
        _ => None,
    }
}

fn format_f32_default(value: f32) -> String {
    format_number(f64::from(value))
}

fn format_display_default(value: impl std::fmt::Display) -> String {
    format!("`{value}`")
}

fn format_option_u64_default(value: Option<u64>) -> String {
    match value {
        Some(value) => value.to_string(),
        None => "null".to_owned(),
    }
}

fn format_points_default(points: &[(f32, f32)]) -> String {
    let pairs = points
        .iter()
        .map(|(x, y)| format!("({}, {})", format_f32_default(*x), format_f32_default(*y)))
        .collect::<Vec<_>>();
    format!("&#91;{}&#93;", pairs.join(", "))
}

#[cfg(test)]
fn documented_leaf_paths() -> std::collections::BTreeSet<Vec<String>> {
    let mut documented = std::collections::BTreeSet::new();

    for field in TONE_FIELDS {
        documented.insert(vec!["tone".to_owned(), (*field).to_owned()]);
    }

    for field in WHITE_BALANCE_FIELDS {
        documented.insert(vec!["white_balance".to_owned(), (*field).to_owned()]);
    }

    for &(field, _, _, _) in MANUAL_METADATA_FIELDS {
        documented.insert(field.split('.').map(str::to_owned).collect());
    }

    for &(field, _, _, _) in MANUAL_LUT_FIELDS {
        documented.insert(field.split('.').map(str::to_owned).collect());
    }

    for channel in HSL_CHANNELS {
        for component in HSL_COMPONENTS {
            documented.insert(vec![
                "hsl".to_owned(),
                (*channel).to_owned(),
                (*component).to_owned(),
            ]);
        }
    }

    for section in [
        "vignette",
        "color_grading",
        "tone_curve",
        "detail",
        "dehaze",
        "noise_reduction",
        "grain",
    ] {
        for display_path in preferred_nested_field_paths(section)
            .expect("documented sections should have preferred paths")
        {
            documented.insert(
                split_field_path(section, display_path)
                    .into_iter()
                    .map(str::to_owned)
                    .collect(),
            );
        }
    }

    documented
}

fn repo_root() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR"))
        .parent()
        .and_then(|path| path.parent())
        .expect("agx-docgen must live under crates/")
        .to_path_buf()
}

fn sanitize_markdown(markdown: &str) -> String {
    let markdown = strip_clap_markdown_title(markdown);
    strip_alias_annotations(&markdown)
}

fn strip_clap_markdown_title(markdown: &str) -> String {
    let Some(first_line_end) = markdown.find('\n') else {
        return markdown.to_owned();
    };

    let first_line = &markdown[..first_line_end];
    if first_line != CLAP_MARKDOWN_TITLE {
        return markdown.to_owned();
    }

    let mut remainder = &markdown[first_line_end + 1..];
    if remainder.starts_with('\n') {
        remainder = &remainder[1..];
    }

    remainder.to_owned()
}

fn strip_alias_annotations(markdown: &str) -> String {
    markdown
        .replace(" [alias: ", " (alias: ")
        .replace(" [aliases: ", " (aliases: ")
        .replace("`] —", "`) —")
        .replace("`] \n", "`) \n")
        .replace("`]\n", "`)\n")
}

#[cfg(test)]
mod tests {
    use super::{
        documented_leaf_paths, generate_preset_reference_to, render_preset_reference, repo_root,
        sanitize_markdown, strip_alias_annotations, strip_clap_markdown_title, GENERATED_HEADER,
        PRESET_PAGE_TITLE,
    };
    use std::collections::BTreeMap;

    fn preset_markdown() -> String {
        let schema = schemars::schema_for!(agx::Parameters);
        render_preset_reference(&schema)
    }

    fn rendered_default_column_by_path(markdown: &str) -> BTreeMap<Vec<String>, String> {
        let mut defaults = BTreeMap::new();

        for line in markdown.lines() {
            if !line.starts_with("| `") {
                continue;
            }

            let columns = line.split('|').map(str::trim).collect::<Vec<_>>();
            if columns.len() < 5 {
                continue;
            }

            let field = columns[1].trim_matches('`');
            let default = columns[3].to_owned();
            let path = field.split('.').map(str::to_owned).collect::<Vec<_>>();
            defaults.insert(path, default);
        }

        defaults
    }

    fn expected_canonical_defaults() -> BTreeMap<Vec<String>, String> {
        let defaults = agx::Parameters::default();
        let mut values = BTreeMap::new();

        values.insert(
            vec!["tone".to_owned(), "exposure".to_owned()],
            fmt_f32(defaults.exposure),
        );
        values.insert(
            vec!["tone".to_owned(), "contrast".to_owned()],
            fmt_f32(defaults.contrast),
        );
        values.insert(
            vec!["tone".to_owned(), "highlights".to_owned()],
            fmt_f32(defaults.highlights),
        );
        values.insert(
            vec!["tone".to_owned(), "shadows".to_owned()],
            fmt_f32(defaults.shadows),
        );
        values.insert(
            vec!["tone".to_owned(), "whites".to_owned()],
            fmt_f32(defaults.whites),
        );
        values.insert(
            vec!["tone".to_owned(), "blacks".to_owned()],
            fmt_f32(defaults.blacks),
        );
        values.insert(
            vec!["white_balance".to_owned(), "temperature".to_owned()],
            fmt_f32(defaults.temperature),
        );
        values.insert(
            vec!["white_balance".to_owned(), "tint".to_owned()],
            fmt_f32(defaults.tint),
        );

        for (channel, value) in [
            ("red", defaults.hsl.red),
            ("orange", defaults.hsl.orange),
            ("yellow", defaults.hsl.yellow),
            ("green", defaults.hsl.green),
            ("aqua", defaults.hsl.aqua),
            ("blue", defaults.hsl.blue),
            ("purple", defaults.hsl.purple),
            ("magenta", defaults.hsl.magenta),
        ] {
            values.insert(
                vec!["hsl".to_owned(), channel.to_owned(), "hue".to_owned()],
                fmt_f32(value.hue),
            );
            values.insert(
                vec![
                    "hsl".to_owned(),
                    channel.to_owned(),
                    "saturation".to_owned(),
                ],
                fmt_f32(value.saturation),
            );
            values.insert(
                vec!["hsl".to_owned(), channel.to_owned(), "luminance".to_owned()],
                fmt_f32(value.luminance),
            );
        }

        values.insert(
            vec!["vignette".to_owned(), "amount".to_owned()],
            fmt_f32(defaults.vignette.amount),
        );
        values.insert(
            vec!["vignette".to_owned(), "shape".to_owned()],
            format!("`{}`", defaults.vignette.shape),
        );

        for (wheel, value) in [
            ("shadows", defaults.color_grading.shadows),
            ("midtones", defaults.color_grading.midtones),
            ("highlights", defaults.color_grading.highlights),
            ("global", defaults.color_grading.global),
        ] {
            values.insert(
                vec![
                    "color_grading".to_owned(),
                    wheel.to_owned(),
                    "hue".to_owned(),
                ],
                fmt_f32(value.hue),
            );
            values.insert(
                vec![
                    "color_grading".to_owned(),
                    wheel.to_owned(),
                    "saturation".to_owned(),
                ],
                fmt_f32(value.saturation),
            );
            values.insert(
                vec![
                    "color_grading".to_owned(),
                    wheel.to_owned(),
                    "luminance".to_owned(),
                ],
                fmt_f32(value.luminance),
            );
        }
        values.insert(
            vec!["color_grading".to_owned(), "balance".to_owned()],
            fmt_f32(defaults.color_grading.balance),
        );

        for (curve, points) in [
            ("rgb", &defaults.tone_curve.rgb.points),
            ("luma", &defaults.tone_curve.luma.points),
            ("red", &defaults.tone_curve.red.points),
            ("green", &defaults.tone_curve.green.points),
            ("blue", &defaults.tone_curve.blue.points),
        ] {
            values.insert(
                vec![
                    "tone_curve".to_owned(),
                    curve.to_owned(),
                    "points".to_owned(),
                ],
                fmt_points(points),
            );
        }

        values.insert(
            vec![
                "detail".to_owned(),
                "sharpening".to_owned(),
                "amount".to_owned(),
            ],
            fmt_f32(defaults.detail.sharpening.amount),
        );
        values.insert(
            vec![
                "detail".to_owned(),
                "sharpening".to_owned(),
                "radius".to_owned(),
            ],
            fmt_f32(defaults.detail.sharpening.radius),
        );
        values.insert(
            vec![
                "detail".to_owned(),
                "sharpening".to_owned(),
                "threshold".to_owned(),
            ],
            fmt_f32(defaults.detail.sharpening.threshold),
        );
        values.insert(
            vec![
                "detail".to_owned(),
                "sharpening".to_owned(),
                "masking".to_owned(),
            ],
            fmt_f32(defaults.detail.sharpening.masking),
        );
        values.insert(
            vec!["detail".to_owned(), "clarity".to_owned()],
            fmt_f32(defaults.detail.clarity),
        );
        values.insert(
            vec!["detail".to_owned(), "texture".to_owned()],
            fmt_f32(defaults.detail.texture),
        );

        values.insert(
            vec!["dehaze".to_owned(), "amount".to_owned()],
            fmt_f32(defaults.dehaze.amount),
        );

        values.insert(
            vec!["noise_reduction".to_owned(), "luminance".to_owned()],
            fmt_f32(defaults.noise_reduction.luminance),
        );
        values.insert(
            vec!["noise_reduction".to_owned(), "color".to_owned()],
            fmt_f32(defaults.noise_reduction.color),
        );
        values.insert(
            vec!["noise_reduction".to_owned(), "detail".to_owned()],
            fmt_f32(defaults.noise_reduction.detail),
        );

        values.insert(
            vec!["grain".to_owned(), "type".to_owned()],
            format!("`{}`", defaults.grain.grain_type),
        );
        values.insert(
            vec!["grain".to_owned(), "amount".to_owned()],
            fmt_f32(defaults.grain.amount),
        );
        values.insert(
            vec!["grain".to_owned(), "size".to_owned()],
            fmt_f32(defaults.grain.size),
        );
        values.insert(
            vec!["grain".to_owned(), "seed".to_owned()],
            defaults
                .grain
                .seed
                .map(|value| value.to_string())
                .unwrap_or_else(|| "null".to_owned()),
        );

        values.insert(
            vec!["metadata".to_owned(), "name".to_owned()],
            "\"\"".to_owned(),
        );
        values.insert(
            vec!["metadata".to_owned(), "version".to_owned()],
            "\"\"".to_owned(),
        );
        values.insert(
            vec!["metadata".to_owned(), "author".to_owned()],
            "\"\"".to_owned(),
        );
        values.insert(
            vec!["metadata".to_owned(), "extends".to_owned()],
            "null".to_owned(),
        );
        values.insert(vec!["lut".to_owned(), "path".to_owned()], "null".to_owned());
        values.insert(
            vec!["lut".to_owned(), "encoding".to_owned()],
            "`srgb`".to_owned(),
        );

        values
    }

    fn fmt_f32(value: f32) -> String {
        let mut formatted = value.to_string();
        if let Some(stripped) = formatted.strip_suffix(".0") {
            formatted = stripped.to_owned();
        }
        formatted
    }

    fn fmt_points(points: &[(f32, f32)]) -> String {
        let pairs = points
            .iter()
            .map(|(x, y)| format!("({}, {})", fmt_f32(*x), fmt_f32(*y)))
            .collect::<Vec<_>>();
        format!("&#91;{}&#93;", pairs.join(", "))
    }

    fn unique_temp_output_path() -> std::path::PathBuf {
        let timestamp = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .expect("system time should be after unix epoch")
            .as_nanos();
        std::env::temp_dir()
            .join(format!(
                "agx-docgen-test-{}-{timestamp}",
                std::process::id()
            ))
            .join("preset.md")
    }

    #[test]
    fn repo_root_points_at_workspace_root() {
        let root = repo_root();

        assert!(root.ends_with("AgX"));
        assert!(root.join("docs/book/src/reference/cli.md").is_absolute());
    }

    #[test]
    fn strip_clap_markdown_title_removes_only_the_known_title() {
        let markdown = "# Command-Line Help for `agx`\n\n## `agx`\n\n###### **Subcommands:**\n";

        let stripped = strip_clap_markdown_title(markdown);

        assert_eq!(stripped, "## `agx`\n\n###### **Subcommands:**\n");
    }

    #[test]
    fn strip_clap_markdown_title_leaves_other_headings_alone() {
        let markdown = "# Something Else\n\n## `agx`\n";

        let stripped = strip_clap_markdown_title(markdown);

        assert_eq!(stripped, markdown);
    }

    #[test]
    fn strip_alias_annotations_rewrites_alias_markers_for_mdbook() {
        let markdown = "* `--hsl-red-hue <HSL_RED_HUE>` [alias: `hsl-red-h`] — Red hue shift\n";

        let sanitized = strip_alias_annotations(markdown);

        assert_eq!(
            sanitized,
            "* `--hsl-red-hue <HSL_RED_HUE>` (alias: `hsl-red-h`) — Red hue shift\n"
        );
    }

    #[test]
    fn sanitize_markdown_applies_title_and_alias_rewrites() {
        let markdown = "# Command-Line Help for `agx`\n\n* `--x` [alias: `y`] — Help\n";

        let sanitized = sanitize_markdown(markdown);

        assert_eq!(sanitized, "* `--x` (alias: `y`) — Help\n");
    }

    #[test]
    fn preset_reference_contains_expected_sections_and_table_headers() {
        let markdown = preset_markdown();

        assert!(markdown.starts_with(&format!("{GENERATED_HEADER}\n{PRESET_PAGE_TITLE}\n")));
        for heading in [
            "## metadata",
            "## tone",
            "## white_balance",
            "## lut",
            "## hsl",
            "## vignette",
            "## color_grading",
            "## tone_curve",
            "## detail",
            "## dehaze",
            "## noise_reduction",
            "## grain",
        ] {
            assert!(
                markdown.contains(heading),
                "missing preset section heading: {heading}"
            );
        }
        assert!(markdown.contains("| Field | Range / Values | Default | Note |"));
        assert!(!markdown.contains(".agx"));
    }

    #[test]
    fn preset_reference_includes_key_ranges_defaults_and_links() {
        let markdown = preset_markdown();

        assert!(markdown.contains("| `tone.exposure` | -5 to 5 | 0 |"));
        assert!(
            markdown.contains("| `white_balance.temperature` | number (no validated range) | 0 |")
        );
        assert!(markdown.contains("| `hsl.red.hue` | -180 to 180 | 0 |"));
        assert!(markdown.contains("| `vignette.shape` | `elliptical`, `circular` | `elliptical` |"));
        assert!(markdown.contains("| `detail.sharpening.radius` | 0.5 to 3 | 1 |"));
        assert!(markdown.contains("| `grain.type` | `fine`, `silver`, `harsh` | `silver` |"));
        assert!(markdown.contains("| `grain.size` | 0 to 100 | 50 |"));
        assert!(markdown.contains("| `tone_curve.rgb.points` | array of &#91;x, y&#93; points, each 0 to 1 | &#91;(0, 0), (1, 1)&#93; |"));
        assert!(markdown.contains(
            "Control points as (input, output) pairs in &#91;0.0, 1.0&#93;, sorted by input."
        ));
        assert!(markdown.contains("metadata.name"));
        assert!(markdown.contains("lut.path"));
        assert!(markdown.contains("lut.encoding"));
        assert!(markdown.contains("../explanation/algorithms/grain.md"));
    }

    #[test]
    fn generate_preset_reference_writes_generated_page() {
        let output_path = unique_temp_output_path();
        let output_path =
            generate_preset_reference_to(&output_path).expect("preset reference should generate");
        let contents =
            std::fs::read_to_string(&output_path).expect("preset file should be readable");

        assert!(contents.starts_with(&format!("{GENERATED_HEADER}\n{PRESET_PAGE_TITLE}\n")));
        assert!(contents.contains("## metadata"));
        assert!(contents.contains("## grain"));
        assert!(!contents.contains(".agx"));

        let _ = std::fs::remove_file(&output_path);
        if let Some(parent) = output_path.parent() {
            let _ = std::fs::remove_dir(parent);
        }
    }

    #[test]
    fn documented_preset_leaf_paths_cover_the_rendered_layout() {
        let markdown = preset_markdown();
        let rendered_paths = rendered_default_column_by_path(&markdown)
            .into_keys()
            .collect::<std::collections::BTreeSet<_>>();

        assert_eq!(documented_leaf_paths(), rendered_paths);
    }

    #[test]
    fn rendered_preset_defaults_match_canonical_runtime_defaults() {
        let rendered_defaults = rendered_default_column_by_path(&preset_markdown());
        let expected_defaults = expected_canonical_defaults();

        assert_eq!(rendered_defaults, expected_defaults);
    }
}
