//! Generates CLI and preset reference pages for the AgX documentation site.
//!
//! Output is written to `docs/book/src/reference/` and consumed by mdbook.

use std::{fs, io, path::PathBuf};

use clap_markdown::MarkdownOptions;

const OUTPUT_DIR: &str = "docs/book/src/reference";
const OUTPUT_FILE: &str = "cli.md";
const GENERATED_HEADER: &str = "<!-- Generated by agx-docgen. Do not edit manually. -->";
const PAGE_TITLE: &str = "# CLI Reference";

fn main() {
    if let Err(error) = generate_cli_reference() {
        eprintln!("agx-docgen: {error}");
        std::process::exit(1);
    }
}

fn generate_cli_reference() -> io::Result<PathBuf> {
    let output_dir = PathBuf::from(OUTPUT_DIR);
    fs::create_dir_all(&output_dir)?;

    let command = agx_cli::build_cli();
    let markdown = clap_markdown::help_markdown_command_custom(
        &command,
        &MarkdownOptions::new().show_footer(false),
    );
    let markdown = strip_renderer_title(&markdown);

    let output_path = output_dir.join(OUTPUT_FILE);
    let contents = format!("{GENERATED_HEADER}\n{PAGE_TITLE}\n\n{markdown}");
    fs::write(&output_path, contents)?;

    println!("generated {}", output_path.display());

    Ok(output_path)
}

fn strip_renderer_title(markdown: &str) -> String {
    let Some(first_line_end) = markdown.find('\n') else {
        return markdown.to_owned();
    };

    let first_line = &markdown[..first_line_end];
    if !first_line.starts_with("# ") {
        return markdown.to_owned();
    }

    let mut remainder = &markdown[first_line_end + 1..];
    if remainder.starts_with('\n') {
        remainder = &remainder[1..];
    }

    remainder.to_owned()
}

#[cfg(test)]
mod tests {
    use super::strip_renderer_title;

    #[test]
    fn strip_renderer_title_removes_only_the_first_heading() {
        let markdown = "# Command-Line Help for `agx`\n\n## `agx`\n\n###### **Subcommands:**\n";

        let stripped = strip_renderer_title(markdown);

        assert_eq!(stripped, "## `agx`\n\n###### **Subcommands:**\n");
    }

    #[test]
    fn strip_renderer_title_leaves_non_heading_content_unchanged() {
        let markdown = "intro text\n\n## `agx`\n";

        let stripped = strip_renderer_title(markdown);

        assert_eq!(stripped, markdown);
    }
}
